### ISSUE TITLE
IndexError: index 23 is out of bounds for axis 1 with size 20

### ISSUE THREAD

**Issue by gr3yknigh1** [xDiaym/poom#27]
# Description

Index Error

# Platform

`Darwin ox-c3.msk.21-school.ru 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64`

# Recreation

```
python3 -m venv .venv
.venv/bin/activate
python3 -m pip install -r requirements.txt
python3 setup.py build_ext --inplace
python3 -m pip install . 
python3 poom.py
```

(Play until second level)

# Logs

```
pygame 2.5.2 (SDL 2.28.3, Python 3.11.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/Users/wittenbb/pog/poom/poom.py", line 6, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/wittenbb/pog/poom/poom/game.py", line 169, in main
    game.run()
  File "/Users/wittenbb/pog/poom/poom/game.py", line 153, in run
    sc.update(dt)
  File "/Users/wittenbb/pog/poom/poom/shared.py", line 97, in update
    self._scene.update(dt)
  File "/Users/wittenbb/pog/poom/poom/game.py", line 106, in update
    self._player.update(dt)
  File "/Users/wittenbb/pog/poom/poom/player.py", line 59, in update
    self._process_keys(dt)
  File "/Users/wittenbb/pog/poom/poom/player.py", line 115, in _process_keys
    self._move(dt, keys)
  File "/Users/wittenbb/pog/poom/poom/player.py", line 97, in _move
    if self._map[int(old.y), int(new.x)] == 0:  # noqa: WPS221
       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 23 is out of bounds for axis 1 with size 20
```

**Comment by xDiaym** [comment]
@gr3yknigh1 wont fix lol
